### PR TITLE
Bump SpecFlow to 3.9.40

### PR DESCRIPTION
**Pull request by godrose**
#### Checklist
- [x] [Sign Allure CLA][cla]
- [x] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Comment by godrose** [comment]
@Bakanych 
New version of SpecFlow has been released

**Comment by godrose** [comment]
@Bakanych Any news?

**Comment by godrose** [comment]
@Bakanych @baev 
Hey there. 
Do you have en ETA for PR approval?
I am planning to update SpecFlow version for my workloads and want to continue using `Allure` as the report tool instead of `LivingDoc` hence the dependency...

Thanks in advance.

**Comment by Bakanych** [comment]
hello @godrose,
We usually specify minimal supported version in dependencies. It doesn't make sense to release new version every time when SpecFlow releases minor or build update.
Why do not just update SpecFlow dependencies directly in your projects?

**Comment by godrose** [comment]
@Bakanych 
Thanks for your reply.

I will check the suggested option and see whether it works.

In this particular case the SpecFlow's latest version adds compatibility to .NET 6 and other features.

So it might make sense to release a servicing version of this package IMHO.

**Pull request closed without merging**
