### PR TITLE
Add parameters and custom name attributes for XUnit

### PR DESCRIPTION
**Pull request by smolchanovsky**
### Context
Description and discussion of the solved problem is here: https://github.com/allure-framework/allure-csharp/issues/309

#### Checklist
- [x] [Sign Allure CLA][cla]
- [ ] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Comment by neparij** [comment]
Hi, @smolchanovsky !
Thank you for contributing to Allure!
Could you sign a CLA on this contribution?

- it would be better to override `GetDisplayName(IAttributeInfo factAttribute, string s)` from Xunit.Sdk.XunitTestCase within Allure.XUnit.AllureXunitTestCase to provide `name` and `fullname` without parameters
- `AllureNameAttribute` and `AllureFullNameAttribute` usage is unnecessarily: `AllureXunitAttribute` is inherited from `FactAttribute` and already have an DisplayName parameter. It will be ambiguous for users.

**Comment by smolchanovsky** [comment]
> Hi, @smolchanovsky ! Thank you for contributing to Allure! Could you sign a CLA on this contribution?
> 
> * it would be better to override `GetDisplayName(IAttributeInfo factAttribute, string s)` from Xunit.Sdk.XunitTestCase within Allure.XUnit.AllureXunitTestCase to provide `name` and `fullname` without parameters
> * `AllureNameAttribute` and `AllureFullNameAttribute` usage is unnecessarily: `AllureXunitAttribute` is inherited from `FactAttribute` and already have an DisplayName parameter. It will be ambiguous for users.

@neparij  hi!
You're right, it will be ambiguous for users. Frankly, I forgot about the `DisplayName` property in `FactAttribute` :)

But one thing bothers me. I'd like to be able to set different values in `name` and `fullName`, so `DisplayName` is not enough. Maybe add an additional field - `FullDisplayName`?

**Comment by neparij** [comment]
> > Hi, @smolchanovsky ! Thank you for contributing to Allure! Could you sign a CLA on this contribution?
> > 
> > * it would be better to override `GetDisplayName(IAttributeInfo factAttribute, string s)` from Xunit.Sdk.XunitTestCase within Allure.XUnit.AllureXunitTestCase to provide `name` and `fullname` without parameters
> > * `AllureNameAttribute` and `AllureFullNameAttribute` usage is unnecessarily: `AllureXunitAttribute` is inherited from `FactAttribute` and already have an DisplayName parameter. It will be ambiguous for users.
> 
> @neparij hi! You're right, it will be ambiguous for users. Frankly, I forgot about the `DisplayName` property in `FactAttribute` :)
> 
> But one thing bothers me. I'd like to be able to set different values in `name` and `fullName`, so `DisplayName` is not enough. Maybe add an additional property - `FullDisplayName`?
> 
> PS: Now I have signed the CLA, but status is still "not signed yet" 🤔

You can use full-qualified name for FullDisplayName. Look at `GetUniqueID()` method in Allure.XUnit.AllureXunitTestCase

CLA assistant fails with ```smolchanovsky seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).```

**Comment by smolchanovsky** [comment]
> You can use full-qualified name for FullDisplayName. Look at GetUniqueID() method in Allure.XUnit.AllureXunitTestCase

Ok, I'll take a look at the method. Thanks

CLA job completed successfully now. I found out that the wrong mail was specified in commits :)

**Comment by 1Playerr** [comment]
Hi, @neparij 

I've decided to resolve PR comments. I've removed redundant attributes `AllureNameAttribute` and `AllureFullNameAttribute` as you suggested and added two methods to build test name and full name. The test's name can be also set via `DisplayName`.

**Review by neparij — APPROVED** [review]

**Pull request merged**
